In [50]:
import random
import pandas as pd
# Load training data
train = pd.read_csv("dummy.csv", skiprows=lambda x: x % 2)
classes_train = [row[1] for row in train_rows]

In [51]:
train

,timestamp,tweet_text,username,all_hashtags,location,followers_count,retweet_count,favorite_count
0,2021-06-05 19:02:22,b'Super excited to present at this conference ...,b'VirnaRossi',"['thresholdconceps', 'aussieED', 'edchat', 'LT...",London/Italy,2377,0,0
1,2021-06-05 19:02:01,"b""\xf0\x9f\x8e\x87 Make one of these super coo...",b'AFTteach',"['TEACH2021', 'EdChat', 'Educhat', 'DistanceLe...","Washington, DC",6333,0,0
2,2021-06-05 19:00:50,b'You can download all of our free weekly math...,b'mashupmath',['edchat'],"Denver, CO",24850,0,3
3,2021-06-05 19:00:33,b'NO COST! 5 new online courses have been rele...,b'NYSCATE',"['edtech', 'edchat']","New York, USA",6107,0,0
4,2021-06-05 19:00:20,"b'""I want to spark a movement\xe2\x80\x94get m...",b'EdReimagined',"['edreimagined', 'edchat']",NaN,8925,0,0
...,...,...,...,...,...,...,...,...
995,2021-06-03 20:36:00,b'INFO: Quick Calculate. Practice order of ope...,b'internet4classr',"['edchat', '3rdchat', '4thchat', '5thchat', 'e...","Memphis, TN",6967,0,1
996,2021-06-03 20:35:03,"b""5 reasons to add a 'flex day' to your school...",b'enrichstudents',"['PD', 'edchat']",New Hampshire,2750,0,0
997,2021-06-03 20:34:14,b'TCEA: YouTube Got Mail #TceaAtTheMovies ---...,b'blewistexas',"['TceaAtTheMovies', 'teachertwitter', 'edutwit...",Central Texas,665,0,0
998,2021-06-03 20:32:02,b'\xf0\x9f\x8e\xac\xf0\x9f\x94\x91\xf0\x9f\x92...,b'EDUcre8ive',"['learning', 'storytelling', 'edchat', 'librar...","Saratoga, California, USA",7450,0,0
999,2021-06-03 20:30:00,"b'If it is approved, candidates wouldn\xe2\x80...",b'EdSource',"['caedu', 'edchat', 'caedchat']","Oakland, CA",20875,1,1

In [59]:
# create a dataframe using texts and lables
trainDF = pd.DataFrame()
trainDF['text'] = train['tweet_text']

In [52]:
# Load testing data
test = pd.read_csv("new_tweets.csv", skiprows=lambda x: x % 2)
classes_test = [row[1] for row in test_rows]

In [53]:
test

,timestamp,tweet_text,username,all_hashtags,followers_count
0,2021-06-04 18:55:01,b'A remarkable statement and one we are so pro...,b'SparxMaths',"['education', 'secondaryeducation', 'edtech', ...",1471
1,2021-06-04 18:50:01,b'ICYMI: Our NEW Spotlight indicators present ...,b'EdNCES',"['EdData', 'coronavirus', 'K12', 'postsec', 'E...",23884
2,2021-06-04 18:49:26,b'Thalmic Labs Myo Armband #edtech #edchat htt...,b'eduappsandmore',"['edtech', 'edchat']",1782
3,2021-06-04 18:44:00,b'Learning happens everywhere - not just insid...,b'pearl_remote',"['EdChat', 'Learning', 'EducationReform', 'Pro...",172
4,2021-06-04 18:43:00,b'We\xe2\x80\x99re excited to announce that a ...,b'GFSFNonProfit',"['CareerChoices', 'edchat']",57
...,...,...,...,...,...
3944,2021-05-27 15:50:34,b'Collaborative Jamboards are great IF your st...,b'emmabpass',"['edutwitter', 'edchat']",3444
3945,2021-05-27 15:48:02,"b""\xf0\x9f\x93\xa2 Register for our June webin...",b'teachingperson',"['edchat', 'schoolleaders', 'headteachers']",2508
3946,2021-05-27 15:45:56,b'Consider applying for the Literacy Collabora...,b'Lesley_CRRLC',"['teachers', 'educators', 'Teaching', 'Literac...",1005
3947,2021-05-27 15:45:14,b'Many American Indian and Alaska Native famil...,b'relnw',"['IndianEd', 'EdChat']",2570
3948,2021-05-27 15:36:45,b'The year that changed everything! @druinok ...,b'gautiersue',"['iteachmath', 'mtbos', 'edtech', 'mathchat', ...",1139

In [54]:
import skipthoughts

class SkipThoughtsVectorizer(object):
    def __init__(self, **kwargs):
        self.model = skipthoughts.load_model()
        self.encoder = skipthoughts.Encoder(self.model)

    def fit_transform(self, raw_documents, y):
        return self.encoder.encode(raw_documents, verbose=False)

    def fit(self, raw_documents, y=None):
        self.fit_transform(raw_documents, y)
        return self

    def transform(self, raw_documents, copy=True):
        return self.fit_transform(raw_documents, None)

In [55]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

# pipeline_skipthought = Pipeline(steps=[('vectorizer', SkipThoughtsVectorizer()),('classifier', LogisticRegression())])
pipeline_tfidf = Pipeline(steps=[('vectorizer', TfidfVectorizer(ngram_range=(1, 2))),('classifier', LogisticRegression())])

#feature_union = ('feature_union', FeatureUnion([('skipthought', SkipThoughtsVectorizer()),('tfidf', TfidfVectorizer(ngram_range=(1, 2))),]))
#pipeline_both = Pipeline(steps=[feature_union,('classifier', LogisticRegression())])

In [58]:
for train_size in (20, 50, len(train)):
    print(train_size, '--------------------------------------')

    # tfidf
    pipeline_tfidf.fit(train[:train_size], classes_train[:train_size])
    print('tfidf', pipeline_tfidf.score(test, classes_test))

20 --------------------------------------
tfidf 1.0
50 --------------------------------------
tfidf 1.0
1000 --------------------------------------
tfidf 1.0